name: Sync
on:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name 'GitHub CI'
          git config --global user.email 'ggaguilar@gmail.com'
          git clone --depth 1 https://Funk66:$TOKEN@github.com/Funk66/playlists.git $HOME/.config/playlister
          cd $HOME/.config/playlister
          git remote set-url origin https://ggaguilar:$TOKEN@bitbucket.org/ggaguilar/playlister.git
      - name: Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install
        run: python3 setup.py install
      - name: Update
        run: playlister update -w
